# https://taskfile.dev

version: '3'

tasks:
  lint:
    dir: recipes
    cmds:
      - cook doctor
  sync:
    cmds:
      - rsync -avh --delete recipes/* "/Users/$USER/Library/Mobile Documents/iCloud~org~cooklang~cooklangapp/Documents/"

