default_units = true
warnings_as_errors = false
recipe_ref_check = true
max_depth = 10

[extensions]
MULTILINE_STEPS = false
COMPONENT_MODIFIERS = true
COMPONENT_NOTE = true
COMPONENT_ALIAS = true
SECTIONS = true
ADVANCED_UNITS = true
MODES = true
TEMPERATURE = true
TEXT_STEPS = true
RANGE_VALUES = true
TIMER_REQUIRES_TIME = true
INTERMEDIATE_PREPARATIONS = true
SPECIAL_METADATA = true
